EJERCICIO 6:
A) sentencia1 > sentencia2 > sentencia3 > sentencia6 > sentencia5
B) sentencia1 > sentencia2 > sentencia3 > sentencia4 > sentencia5

EJERCICIO 7:
A) sentencia1 > sentencia2 > sentencia3 > sentencia4
B) sentencia1 > sentencia2 > sentencia4

EJERCICIO 8:
A)Como no hay excepción, se mostrará por pantalla:

Valor final del try: 44
Valor final del finally: 45
Valor antes del return: 46
46

B)Como hay excepción y la puedo manejar se mostrará:

Valor final del catch  :43
Valor final del finally: 44
Valor antes del return: 45
45

C)Hay excepcion en método:

Valor final del finally: 2        //------finally se ejecuta siempre
Excepcion en metodo() 
java.lang.NumberFormatException: For input string: "w"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at Ej08.Ej08.metodo(Ej08.java:22)
	at Ej08.Ej08.main(Ej08.java:42)

EJERCICIO 9:
A)sentencia1 > sentencia2 > sentencia4 > sentencia6
B)sentencia1 > sentencia2 > sentencia3 > sentencia6
C)sentencia1 > sentencia2 > sentencia5 > sentencia6